-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addon_features (
  id integer NOT NULL DEFAULT nextval('addon_features_id_seq'::regclass),
  addon_id integer NOT NULL,
  feature_name character varying NOT NULL,
  feature_description text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT addon_features_pkey PRIMARY KEY (id),
  CONSTRAINT addon_features_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES public.addons(id)
);
CREATE TABLE public.addons (
  id integer NOT NULL DEFAULT nextval('addons_id_seq'::regclass),
  name character varying NOT NULL,
  description text,
  price_type character varying NOT NULL,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT addons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.purchased_package_with_features (
  id integer NOT NULL DEFAULT nextval('purchased_package_with_features_id_seq'::regclass),
  user_id bigint NOT NULL,
  purchase_date timestamp without time zone DEFAULT now(),
  expiration_date date NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  features jsonb NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT purchased_package_with_features_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ppwf_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.company_brand_kit_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id bigint,
  building_type character varying,
  business_email character varying,
  has_proventous_id character varying,
  proventous_id character varying,
  business_name character varying,
  contact_number character varying,
  preferred_contact character varying,
  industry ARRAY,
  year_started integer,
  primary_location jsonb,
  behind_brand text,
  current_customers ARRAY,
  want_to_attract text,
  team_description text,
  desired_emotion character varying,
  target_professions ARRAY,
  reach_locations ARRAY,
  age_groups ARRAY,
  spending_habits ARRAY,
  interaction_methods ARRAY,
  customer_challenges text,
  customer_motivation text,
  audience_behavior ARRAY,
  customer_choice text,
  culture_words ARRAY,
  team_traditions text,
  team_highlights text,
  reason1 character varying,
  reason2 character varying,
  reason3 character varying,
  brand_soul character varying,
  brand_tone ARRAY,
  brand1 text,
  brand2 text,
  brand3 text,
  brand_avoid text,
  mission_statement text,
  long_term_vision text,
  core_values ARRAY,
  brand_personality ARRAY,
  has_logo character varying,
  logo_action ARRAY,
  preferred_colors ARRAY,
  colors_to_avoid ARRAY,
  font_styles ARRAY,
  design_style ARRAY,
  logo_type ARRAY,
  imagery_style ARRAY,
  inspiration_links text,
  brand_kit_use ARRAY,
  brand_elements ARRAY,
  file_formats ARRAY,
  primary_goal text,
  short_term_goals text,
  mid_term_goals text,
  long_term_goal text,
  big_picture_vision text,
  success_metrics ARRAY,
  business_description text,
  inspiration text,
  target_interests ARRAY,
  current_interests ARRAY,
  special_notes text,
  timeline character varying,
  approver character varying,
  reference_materials text,
  current_step integer DEFAULT 1,
  progress_percentage integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  spending_type character varying,
  secondary_audience text,
  emotional_goal character varying,
  culture_description text,
  business_stage character varying,
  CONSTRAINT company_brand_kit_forms_pkey PRIMARY KEY (id),
  CONSTRAINT company_brand_kit_forms_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organization_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id bigint,
  building_type character varying NOT NULL DEFAULT 'organization'::character varying,
  organization_name character varying,
  social_media_goals text,
  brand_uniqueness text,
  desired_emotion character varying,
  target_platforms ARRAY,
  content_types ARRAY,
  deliverables ARRAY,
  timeline character varying,
  main_contact character varying,
  additional_info text,
  reference_materials text,
  current_step integer DEFAULT 1,
  progress_percentage integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_forms_pkey PRIMARY KEY (id),
  CONSTRAINT organization_forms_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.package_feature_comments (
  id integer NOT NULL DEFAULT nextval('package_feature_comments_id_seq'::regclass),
  package_feature_id integer NOT NULL,
  user_id bigint NOT NULL,
  comment_text text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT package_feature_comments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_package_feature FOREIGN KEY (package_feature_id) REFERENCES public.package_features(id)
);
CREATE TABLE public.package_features (
  id integer NOT NULL DEFAULT nextval('package_features_id_seq'::regclass),
  package_id integer NOT NULL,
  feature_name character varying NOT NULL,
  feature_description text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT package_features_pkey PRIMARY KEY (id),
  CONSTRAINT package_features_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.package_purchases (
  id integer NOT NULL DEFAULT nextval('package_purchases_id_seq'::regclass),
  user_id integer NOT NULL,
  package_id integer NOT NULL,
  purchase_date timestamp without time zone DEFAULT now(),
  expiration_date date NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'expired'::character varying, 'cancelled'::character varying]::text[])),
  total_amount numeric NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  features jsonb,
  CONSTRAINT package_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT package_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT package_purchases_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.packages (
  id integer NOT NULL DEFAULT nextval('packages_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  duration_days integer NOT NULL CHECK (duration_days > 0),
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT packages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_service_forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id bigint,
  building_type character varying DEFAULT 'product'::character varying,
  product_name character varying,
  product_description text,
  industry ARRAY,
  want_to_attract text,
  mission_story text,
  desired_emotion character varying,
  brand_tone character varying,
  target_audience_profile text,
  reach_locations ARRAY,
  brand_personality ARRAY,
  design_style ARRAY,
  preferred_colors ARRAY,
  colors_to_avoid ARRAY,
  competitors text,
  brand_kit_use ARRAY,
  brand_elements ARRAY,
  file_formats ARRAY,
  platform_support ARRAY,
  timeline character varying,
  primary_location character varying,
  preferred_contact character varying,
  approver character varying,
  special_notes text,
  reference_materials text,
  current_step integer DEFAULT 1,
  progress_percentage integer DEFAULT 0,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_service_forms_pkey PRIMARY KEY (id),
  CONSTRAINT product_service_forms_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.purchased_addons (
  id integer NOT NULL DEFAULT nextval('purchased_addons_id_seq'::regclass),
  user_id integer NOT NULL,
  addon_id integer NOT NULL,
  purchase_date timestamp without time zone DEFAULT now(),
  base_price numeric NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  created_at timestamp without time zone DEFAULT now(),
  duration integer,
  price_type character varying DEFAULT 'one-time'::character varying,
  CONSTRAINT purchased_addons_pkey PRIMARY KEY (id),
  CONSTRAINT purchased_addons_addon_id_fkey FOREIGN KEY (addon_id) REFERENCES public.addons(id),
  CONSTRAINT purchased_addons_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.purchased_package_with_features (
  id integer NOT NULL DEFAULT nextval('purchased_package_with_features_id_seq'::regclass),
  user_id bigint NOT NULL,
  purchase_date timestamp without time zone DEFAULT now(),
  expiration_date date NOT NULL,
  status character varying DEFAULT 'active'::character varying,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  features jsonb NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT purchased_package_with_features_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ppwf_user FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email character varying NOT NULL UNIQUE,
  password character varying NOT NULL,
  email_verified_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  fullname character varying,
  phone_number character varying,
  address text,
  role character varying NOT NULL DEFAULT 'user'::character varying,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);