-- Brand Kit Forms Table for MariaDB
-- This table matches the exact structure of company_brand_kit_forms

-- Create the brand_kit_forms table
CREATE TABLE IF NOT EXISTS brand_kit_forms (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  user_id BIGINT,
  building_type VARCHAR(255),
  business_email VARCHAR(255),
  has_proventous_id VARCHAR(255),
  proventous_id VARCHAR(255),
  business_name VARCHAR(255),
  contact_number VARCHAR(255),
  preferred_contact VARCHAR(255),
  industry JSON, 
  year_started INT,
  primary_location JSON,
  behind_brand TEXT,
  current_customers JSON,
  want_to_attract TEXT,
  team_description TEXT,
  desired_emotion VARCHAR(255),
  target_professions JSON,
  reach_locations JSON,
  age_groups JSON,
  spending_habits JSON,
  interaction_methods JSON,
  customer_challenges TEXT,
  customer_motivation TEXT,
  audience_behavior JSON,
  customer_choice TEXT,
  culture_words JSON,
  team_traditions TEXT,
  team_highlights TEXT,
  reason1 VARCHAR(255),
  reason2 VARCHAR(255),
  reason3 VARCHAR(255),
  brand_soul VARCHAR(255),
  brand_tone JSON,
  brand1 TEXT,
  brand2 TEXT,
  brand3 TEXT,
  brand_avoid TEXT,
  mission_statement TEXT,
  long_term_vision TEXT,
  core_values JSON,
  brand_personality JSON,
  has_logo VARCHAR(255),
  logo_action JSON,
  preferred_colors JSON,
  colors_to_avoid JSON,
  font_styles JSON,
  design_style JSON,
  logo_type JSON,
  imagery_style JSON,
  inspiration_links TEXT,
  brand_kit_use JSON,
  brand_elements JSON,
  file_formats JSON,
  primary_goal TEXT,
  short_term_goals TEXT,
  mid_term_goals TEXT,
  long_term_goal TEXT,
  big_picture_vision TEXT,
  success_metrics JSON,
  business_description TEXT,
  inspiration TEXT,
  target_interests JSON,
  current_interests JSON,
  special_notes TEXT,
  timeline VARCHAR(255),
  approver VARCHAR(255),
  reference_materials TEXT,
  current_step INT DEFAULT 1,
  progress_percentage INT DEFAULT 0,
  is_completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  
  -- Indexes for better performance
  INDEX idx_user_id (user_id),
  INDEX idx_created_at (created_at),
  INDEX idx_is_completed (is_completed),
  INDEX idx_business_email (business_email)
);

-- Add comments for documentation
ALTER TABLE brand_kit_forms 
COMMENT = 'Brand Kit Forms table matching company_brand_kit_forms structure';

-- Show table structure
DESCRIBE brand_kit_forms;
